import type { Metadata } from 'next'

import LoadScripts from '@/components/scripts/load-scripts'
import { Toaster } from '@/components/ui/toaster'
import helper from '@/lib/helper'

import './globals.css'

export const metadata: Metadata = {
    title: 'SB themes',
    description: 'Generated by AppStoneLab',
    openGraph: {
        ...helper.openGraphData,
        url: process.env.NEXT_PUBLIC_APP_URL + '/',
        type: 'website',
    },
    alternates: {
        canonical: `${process.env.NEXT_PUBLIC_APP_URL}`,
    },
    robots: {
        index: true,
        follow: true,
    },
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className="bg-white font-plus-jakarata text-base/5 font-normal text-gray antialiased">
                {children}
                <Toaster />
                <LoadScripts />
            </body>
        </html>
    )
}
